AnnaStaySia
goncharovastacy/Project2 pull request #20
Opened 2023-02-27 19:26 UTC by AnnaStaySia

Добавила секцию "услуги"

2023-02-28 07:45 UTC, goncharovastacy requested changes

2023-02-28 07:45 UTC, goncharovastacy commented on css/services.css
> +max-width: 1340px;
max-width отличается от той, что у нас в контейнере, надо просто обернуть в контейнер

2023-02-28 07:45 UTC, goncharovastacy commented on css/services.css
> +    position: relative;
Не очень поняла зачем позиция relative. Но буду рада есть обЪяснишь 😅

2023-02-28 07:45 UTC, goncharovastacy commented on css/services.css
> +    width: 330px;
Размеры от того, что дано в макете отличаются

2023-03-01 17:19 UTC, AnnaStaySia commented on css/services.css
> +    position: relative;
чтобы текст был поверх картинки - очень удобный способ

2023-03-01 17:19 UTC, AnnaStaySia commented on css/services.css
> +    width: 330px;
поправила

2023-03-01 18:50 UTC, closed without merging